<?php

/**
 * @file
 * Provides Cosign authentication provider.
 */


/**
 * Implements hook_form_alter().
 */
function cosign_form_alter(&$form, \Drupal\Core\Form\FormStateInterface &$form_state, $form_id) {
  if ($form_id == "cosign_admin") {
    $form_state->disableCache();
  }
/*Haven't tested this. Not sure if its necessary
  if ($form_id == "user_login_block") {
    $form['#action'] = 'user/login';
    $form['name']['#access'] = FALSE;
    $form['pass']['#access'] = FALSE;
    $form['submit']['#access'] = FALSE;
    $form['links']['#value'] = '<a href="https://' . $_SERVER['HTTP_HOST'] . request_uri() . '">Login</a>';
  }
*/

  if ($form_id == "user_form") {
    $the_user = \Drupal::currentUser();
    if (!in_array('administrator', $the_user->getRoles())) {
      if (isset($form['account']['name'])) {
        $form['account']['name']['#type'] = 'hidden';
      }
      $form['account']['pass']['#access'] = FALSE;
      $form['account']['current_pass']['#access'] = FALSE;
      //this can't be updated without the prior two by default. this may need to be a setting?
      $form['account']['mail']['#access'] = FALSE;
    }
  }
}

/**
 * Implements hook_help().
 */
function cosign_help($path, $arg) {
  switch ($path) {
    case 'admin/modules#description':
      return t("Allows users to authenticate via Cosign.");

    case "admin/help#cosign":
      return '<p>' . t("Allows users to authenticate via Cosign") . '</p>';
  }
}
